import { supabase } from "./server/src/db.js";

async function init() {
  console.log("Checking tables...");
  
  // Create settings table
  const { error: settingsError } = await supabase.from('settings').select('*').limit(1);
  if (settingsError && settingsError.code === '42P01') {
    console.log("Table 'settings' does not exist. Please create it in Supabase SQL Editor:");
    console.log(`
      CREATE TABLE IF NOT EXISTS settings (
        key TEXT PRIMARY KEY,
        value JSONB NOT NULL
      );
    `);
  } else {
    console.log("'settings' table exists.");
  }

  // Create attendance table
  const { error: attendanceError } = await supabase.from('attendance').select('*').limit(1);
  if (attendanceError && attendanceError.code === '42P01') {
    console.log("Table 'attendance' does not exist. Please create it in Supabase SQL Editor:");
    console.log(`
      CREATE TABLE IF NOT EXISTS attendance (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        registration_id BIGINT REFERENCES registrations(id) ON DELETE CASCADE,
        date DATE NOT NULL,
        status TEXT NOT NULL,
        created_at TIMESTAMPTZ DEFAULT NOW(),
        UNIQUE(registration_id, date)
      );
    `);
  } else {
    console.log("'attendance' table exists.");
  }
}

init();
