[dotenv@17.3.1] injecting env (12) from server\.env -- tip: ≡ƒñû agentic secret storage: https://dotenvx.com/as2
-- NiKii Digital Data Export --

-- Courses Data
INSERT INTO courses (id, title, duration, description, icon, color, features, "imageUrl", "isActive", "isPromoted", "badgeText", "createdAt") VALUES (2, 'Summer Computer Course (SCC)', '2 Months', 'Perfect holiday program focusing on MS Office, Internet, and Digital Literacy.', 'bi-sun-fill', 'from-orange-400 to-red-500', '["MS Office","Internet Basics","Typing Master"]'::jsonb, NULL, true, true, '50% OFF', '2026-03-16T13:08:00.143914+00:00');
INSERT INTO courses (id, title, duration, description, icon, color, features, "imageUrl", "isActive", "isPromoted", "badgeText", "createdAt") VALUES (3, 'Kids Computer Application (KCA)', '3 Months', 'Engaging curriculum for youngsters to master basic operations and creative tools.', 'bi-controller', 'from-pink-500 to-rose-600', '["MS Paint","Logic Games","Basic Typing"]'::jsonb, NULL, true, false, NULL, '2026-03-16T13:08:00.143914+00:00');
INSERT INTO courses (id, title, duration, description, icon, color, features, "imageUrl", "isActive", "isPromoted", "badgeText", "createdAt") VALUES (4, 'Junior Computer Application (JCA)', '6 Months', 'Foundational course for school students covering essential academic computing.', 'bi-mortarboard-fill', 'from-indigo-500 to-purple-600', '["Adv. MS Office","Intro to Web","Digital Ethics"]'::jsonb, NULL, true, false, NULL, '2026-03-16T13:08:00.143914+00:00');
INSERT INTO courses (id, title, duration, description, icon, color, features, "imageUrl", "isActive", "isPromoted", "badgeText", "createdAt") VALUES (5, 'Diploma in Computer Application (DCA)', '6 Months', 'Most popular professional diploma for office management and data operations.', 'bi-file-earmark-spreadsheet-fill', 'from-blue-500 to-cyan-600', '["DTP Basics","Accounting Intro","Database Mgmt"]'::jsonb, NULL, true, false, NULL, '2026-03-16T13:08:00.143914+00:00');
INSERT INTO courses (id, title, duration, description, icon, color, features, "imageUrl", "isActive", "isPromoted", "badgeText", "createdAt") VALUES (6, 'Diploma in Computer Programming (DCP)', '6 Months', 'Start your coding journey with fundamental logic and multiple programming languages.', 'bi-code-slash', 'from-emerald-500 to-teal-600', '["C / C++","Data Structures","Logic Building"]'::jsonb, NULL, true, false, NULL, '2026-03-16T13:08:00.143914+00:00');
INSERT INTO courses (id, title, duration, description, icon, color, features, "imageUrl", "isActive", "isPromoted", "badgeText", "createdAt") VALUES (7, 'Diploma in Web Designing (DWD)', '6 Months', 'Transform into a web developer by learning modern design and front-end tech.', 'bi-layout-text-window-reverse', 'from-orange-500 to-amber-600', '["HTML5 / CSS3","Bootstrap/UI","JavaScript"]'::jsonb, NULL, true, false, NULL, '2026-03-16T13:08:00.143914+00:00');
INSERT INTO courses (id, title, duration, description, icon, color, features, "imageUrl", "isActive", "isPromoted", "badgeText", "createdAt") VALUES (8, 'Diploma in DeskTop Publishing (DDTP)', '6 Months', 'Master professional graphic designing and document publishing tools.', 'bi-palette-fill', 'from-violet-500 to-purple-600', '["Photoshop","CorelDraw","PageMaker"]'::jsonb, NULL, true, false, NULL, '2026-03-16T13:08:00.143914+00:00');
INSERT INTO courses (id, title, duration, description, icon, color, features, "imageUrl", "isActive", "isPromoted", "badgeText", "createdAt") VALUES (9, 'Diploma in Financial Accounting (DFA)', '6 Months', 'Professional accounting course with GST and computerized inventory management.', 'bi-calculator-fill', 'from-emerald-600 to-green-700', '["Tally Prime","GST Filing","Inventory"]'::jsonb, NULL, true, false, NULL, '2026-03-16T13:08:00.143914+00:00');
INSERT INTO courses (id, title, duration, description, icon, color, features, "imageUrl", "isActive", "isPromoted", "badgeText", "createdAt") VALUES (10, 'Diploma in Hardware & Networking (DHN)', '6 Months', 'Learn PC assembly, troubleshooting, and professional network management.', 'bi-cpu-fill', 'from-slate-600 to-gray-700', '["PC Assembly","Networking","Troubleshooting"]'::jsonb, NULL, true, false, NULL, '2026-03-16T13:08:00.143914+00:00');
INSERT INTO courses (id, title, duration, description, icon, color, features, "imageUrl", "isActive", "isPromoted", "badgeText", "createdAt") VALUES (11, 'Tally Prime Professional', '4 Months', 'Specialized course for modern business accounting and financial reports.', 'bi-currency-rupee', 'from-sky-500 to-blue-600', '["Voucher Entry","E-Way Bill","Balance Sheet"]'::jsonb, NULL, true, false, NULL, '2026-03-16T13:08:00.143914+00:00');

-- Registrations Data
INSERT INTO registrations (id, "fullName", email, gender, "dateOfBirth", address, "highestQualification", "schoolCollegeName", "yearOfStudy", "mobileNumber", "preferredBatchTime", "courseSelected", "howDidYouHear", "paymentMode", "promoCode", status, "createdAt") VALUES (1, 'Rajesh Rajesh', 'mallappaganiga04@gmail.com', 'Male', '2007-02-26', 'no1,anthiyur', 'UG & PG (Any Degree)', 'JKKMCT', 'B.Tech-IT and II-Year', '+918015599681', 'Batch - I (9.30am - 11.30am)', 'Junior Computer Application (JCA)', 'Friends / Relatives', 'Offline Mode', NULL, 'Confirmed', '2026-03-16T13:50:36.260Z');
INSERT INTO registrations (id, "fullName", email, gender, "dateOfBirth", address, "highestQualification", "schoolCollegeName", "yearOfStudy", "mobileNumber", "preferredBatchTime", "courseSelected", "howDidYouHear", "paymentMode", "promoCode", status, "createdAt") VALUES (2, 'Rajesh.M', 'mallappaganiga04@gmail.com', 'Male', '2007-02-26', 'NO 1,Anthiyur', 'UG & PG (Any Degree)', 'JKKMCT', 'II-Year - B.Tech-it', '+918015599681', 'Batch - I (9.30am - 11.30am)', 'Kids Computer Application (KCA)', 'WhatsApp', 'Offline Mode', NULL, 'Pending', '2026-03-16T14:47:14.477Z');
INSERT INTO registrations (id, "fullName", email, gender, "dateOfBirth", address, "highestQualification", "schoolCollegeName", "yearOfStudy", "mobileNumber", "preferredBatchTime", "courseSelected", "howDidYouHear", "paymentMode", "promoCode", status, "createdAt") VALUES (3, 'Aathiselva.M', 'rajeshrcb1817@gmail.com', 'Male', '2007-10-31', 'fdla;fjlfkjdflk', 'Class 11 to 12', 'JKKMCT', '10 std', '+919344012456', 'Batch - I (9.30am - 11.30am)', 'Diploma in Hardware & Networking (DHN)', 'Friends / Relatives', 'Offline Mode', NULL, 'Pending', '2026-03-16T15:08:13.041Z');

-- Resetting sequences to prevent ID conflicts
SELECT setval(pg_get_serial_sequence('registrations', 'id'), coalesce(max(id), 1)) FROM registrations;
SELECT setval(pg_get_serial_sequence('courses', 'id'), coalesce(max(id), 1)) FROM courses;
